language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=28
    - BUILD_TOOLS_VER=28.0.3

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$BUILD_TOOLS_VER
    - android-$ANDROID_API_LEVEL

notifications:
  email: false

script:
  - ./gradlew clean build
